/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package innova_producciones;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author felix
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_menu = new javax.swing.JLabel();
        imagen_principal = new javax.swing.JLabel();
        label_cliente = new javax.swing.JLabel();
        label_personal = new javax.swing.JLabel();
        label_inventario = new javax.swing.JLabel();
        label_eventos = new javax.swing.JLabel();
        Background_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INNOVA PRODUCCIONES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_menu.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        label_menu.setForeground(new java.awt.Color(255, 255, 255));
        label_menu.setText("MENU PRINCIPAL");
        getContentPane().add(label_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 40));

        imagen_principal.setText("jLabel3");
        getContentPane().add(imagen_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 520, 400));

        label_cliente.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        label_cliente.setForeground(new java.awt.Color(255, 255, 255));
        label_cliente.setText("Clientes");
        label_cliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_clienteMouseMoved(evt);
            }
        });
        getContentPane().add(label_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, 50));

        label_personal.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        label_personal.setForeground(new java.awt.Color(255, 255, 255));
        label_personal.setText("Personal");
        label_personal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_personalMouseMoved(evt);
            }
        });
        getContentPane().add(label_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 40));

        label_inventario.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        label_inventario.setForeground(new java.awt.Color(255, 255, 255));
        label_inventario.setText("Control de Inventario");
        label_inventario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_inventarioMouseMoved(evt);
            }
        });
        getContentPane().add(label_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, 50));

        label_eventos.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        label_eventos.setForeground(new java.awt.Color(255, 255, 255));
        label_eventos.setText("Eventos");
        label_eventos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_eventosMouseMoved(evt);
            }
        });
        getContentPane().add(label_eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 160, 40));

        Background_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/innova_producciones/abstracto-azul-3d-fondos-hd-4389df3.jpg"))); // NOI18N
        Background_principal.setText("jLabel1");
        Background_principal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Background_principalMouseMoved(evt);
            }
        });
        getContentPane().add(Background_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 810, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_clienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_clienteMouseMoved
        label_cliente.setForeground(Color.yellow);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("clients.png"));
        imagen_principal.setIcon(icon);
        
    }//GEN-LAST:event_label_clienteMouseMoved

    private void Background_principalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background_principalMouseMoved
        label_cliente.setForeground(Color.WHITE);
        label_personal.setForeground(Color.WHITE);
        label_inventario.setForeground(Color.WHITE);
        label_eventos.setForeground(Color.WHITE);
    }//GEN-LAST:event_Background_principalMouseMoved

    private void label_personalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_personalMouseMoved
        label_personal.setForeground(Color.yellow);
        ImageIcon icon = new ImageIcon(getClass().getResource("personal.png"));
        imagen_principal.setIcon(icon);
    }//GEN-LAST:event_label_personalMouseMoved

    private void label_inventarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_inventarioMouseMoved
        label_inventario.setForeground(Color.yellow);
        ImageIcon icon = new ImageIcon(getClass().getResource("invent.png"));
        imagen_principal.setIcon(icon);
    }//GEN-LAST:event_label_inventarioMouseMoved

    private void label_eventosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_eventosMouseMoved
        label_eventos.setForeground(Color.yellow);
        ImageIcon icon = new ImageIcon(getClass().getResource("events.png"));
        imagen_principal.setIcon(icon);
    }//GEN-LAST:event_label_eventosMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_principal;
    private javax.swing.JLabel imagen_principal;
    private javax.swing.JLabel label_cliente;
    private javax.swing.JLabel label_eventos;
    private javax.swing.JLabel label_inventario;
    private javax.swing.JLabel label_menu;
    private javax.swing.JLabel label_personal;
    // End of variables declaration//GEN-END:variables
}
