/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package innova_producciones;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author felix
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        Image img = Toolkit.getDefaultToolkit().createImage(getClass().getResource("innova.png")).getScaledInstance(520, 300, 0);
        imagen_principal.setIcon(new ImageIcon(img));
        this.conectarBaseDatos();
        /*try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(connection);
            
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
    }
    //String connection= "jdbc:sqlserver://localhost:1433;databaseName=INNOVA;user=innova;password=12345";
    //Connection con;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_inventario = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jd_personal = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_tablaPersonal = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        label_menu = new javax.swing.JLabel();
        imagen_principal = new javax.swing.JLabel();
        label_cliente = new javax.swing.JLabel();
        label_personal = new javax.swing.JLabel();
        label_inventario = new javax.swing.JLabel();
        label_eventos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Background_principal = new javax.swing.JLabel();

        jd_inventario.setForeground(new java.awt.Color(0, 0, 51));
        jd_inventario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Inventario Propio");
        jd_inventario.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, 40));
        jd_inventario.getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 10));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo");
        jd_inventario.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 50, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/innova_producciones/tela-polar-azul-marino.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jd_inventario.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 530));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jd_inventario.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));
        jd_inventario.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 160, -1));
        jd_inventario.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 160, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripcion");
        jd_inventario.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/innova_producciones/buttoncolor.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");
        jd_inventario.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 90, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/innova_producciones/Delete.PNG"))); // NOI18N
        jLabel9.setText("jLabel9");
        jd_inventario.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 50, 40));

        jTable1.setForeground(new java.awt.Color(0, 0, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombe", "Descripcion", "En Uso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jd_inventario.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 490, 210));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/innova_producciones/Modify.PNG"))); // NOI18N
        jLabel10.setText("jLabel10");
        jd_inventario.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 50, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jd_inventario.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/innova_producciones/textura-fondo-azul-1573.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jd_inventario.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 530));

        jd_personal.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_personalWindowOpened(evt);
            }
        });

        jt_tablaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Telefono", "Nombre", "Puesto"
            }
        ));
        jScrollPane4.setViewportView(jt_tablaPersonal);

        jd_personal.getContentPane().add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jScrollPane3.setBorder(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(200, 200));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INNOVA PRODUCCIONES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_menu.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        label_menu.setForeground(new java.awt.Color(255, 255, 255));
        label_menu.setText("MENU PRINCIPAL");
        getContentPane().add(label_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 40));

        imagen_principal.setText("jLabel3");
        getContentPane().add(imagen_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 520, 400));

        label_cliente.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        label_cliente.setForeground(new java.awt.Color(255, 255, 255));
        label_cliente.setText("Clientes");
        label_cliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_clienteMouseMoved(evt);
            }
        });
        getContentPane().add(label_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, 50));

        label_personal.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        label_personal.setForeground(new java.awt.Color(255, 255, 255));
        label_personal.setText("Personal");
        label_personal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_personalMouseMoved(evt);
            }
        });
        getContentPane().add(label_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 40));

        label_inventario.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        label_inventario.setForeground(new java.awt.Color(255, 255, 255));
        label_inventario.setText("Control de Inventario");
        label_inventario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_inventarioMouseMoved(evt);
            }
        });
        label_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_inventarioMouseClicked(evt);
            }
        });
        getContentPane().add(label_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, 50));

        label_eventos.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        label_eventos.setForeground(new java.awt.Color(255, 255, 255));
        label_eventos.setText("Eventos");
        label_eventos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label_eventosMouseMoved(evt);
            }
        });
        getContentPane().add(label_eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 160, 40));

        jButton1.setText("Prueba Base");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        Background_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/innova_producciones/abstracto-azul-3d-fondos-hd-4389df3.jpg"))); // NOI18N
        Background_principal.setText("jLabel1");
        Background_principal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Background_principalMouseMoved(evt);
            }
        });
        getContentPane().add(Background_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 810, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_clienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_clienteMouseMoved
        label_cliente.setForeground(Color.yellow);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("clients.png"));
        imagen_principal.setIcon(icon);
        
    }//GEN-LAST:event_label_clienteMouseMoved

    private void Background_principalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background_principalMouseMoved
        label_cliente.setForeground(Color.WHITE);
        label_personal.setForeground(Color.WHITE);
        label_inventario.setForeground(Color.WHITE);
        label_eventos.setForeground(Color.WHITE);
        Image img = Toolkit.getDefaultToolkit().createImage(getClass().getResource("innova.png")).getScaledInstance(520, 300, 0);
        imagen_principal.setIcon(new ImageIcon(img));
        
    }//GEN-LAST:event_Background_principalMouseMoved

    private void label_personalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_personalMouseMoved
        label_personal.setForeground(Color.yellow);
        ImageIcon icon = new ImageIcon(getClass().getResource("personal.png"));
        imagen_principal.setIcon(icon);
    }//GEN-LAST:event_label_personalMouseMoved

    private void label_inventarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_inventarioMouseMoved
        label_inventario.setForeground(Color.yellow);
        ImageIcon icon = new ImageIcon(getClass().getResource("invent.png"));
        imagen_principal.setIcon(icon);
    }//GEN-LAST:event_label_inventarioMouseMoved

    private void label_eventosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_eventosMouseMoved
        label_eventos.setForeground(Color.yellow);
        ImageIcon icon = new ImageIcon(getClass().getResource("events.png"));
        imagen_principal.setIcon(icon);
    }//GEN-LAST:event_label_eventosMouseMoved

    private void label_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_inventarioMouseClicked
        jd_inventario.setVisible(true);
        jd_inventario.setLocationRelativeTo(this);
        jd_inventario.pack();
        jd_inventario.setModal(true);
        
    }//GEN-LAST:event_label_inventarioMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jd_personal.setModal(true);
        this.jd_personal.pack();
        this.jd_personal.setLocationRelativeTo(this);
        this.jd_personal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jd_personalWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_personalWindowOpened
        String[] columnas = new String[4];
        columnas[0] = "ID";
        columnas[1] = "Telefono";
        columnas[2] = "Nombre";
        columnas[3] = "Puesto";
        int size = conteoParaPersonal();
        String[][] contenido = new String[size][4];
        int[] id = this.idPersonal();
        int[] telefono = this.telefonoPersonal();
        String[] nombre = this.nombrePersonal();
        String[] puesto = this.puestoContactos();
        for (int i = 0; i < size; i++) {
            contenido[i][0] = id[i]+ "";
            contenido[i][1] = telefono[i]+ "";
            contenido[i][2] = nombre[i]+ "";
            contenido[i][3] = puesto[i]+ "";
        }
        DefaultTableModel modelo = new DefaultTableModel(contenido, columnas);
        jt_tablaPersonal.setModel(modelo);
    }//GEN-LAST:event_jd_personalWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_principal;
    private javax.swing.JLabel imagen_principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JDialog jd_inventario;
    private javax.swing.JDialog jd_personal;
    private javax.swing.JTable jt_tablaPersonal;
    private javax.swing.JLabel label_cliente;
    private javax.swing.JLabel label_eventos;
    private javax.swing.JLabel label_inventario;
    private javax.swing.JLabel label_menu;
    private javax.swing.JLabel label_personal;
    // End of variables declaration//GEN-END:variables
    Connection connect;
    
    public void conectarBaseDatos() {
        try {
            String connectionUrl = "jdbc:sqlserver://;database=TablasLenguajes;integratedSecurity=true;";
            connect = DriverManager.getConnection(connectionUrl);
            System.out.println("Se ha conectado exitosamente.");
        } catch (SQLException ex) {
            System.out.println("Ha ocurrido un error.");
            ex.printStackTrace();
        }
    }
    
    public int conteoParaPersonal() {
        int temp = 0;
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select count(id) from dbo.Personal;");
            while (rs.next()) {
                temp = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return temp;
    }
    
    public int[] idPersonal() {
        int[] id = new int[conteoParaPersonal()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select id from dbo.Personal;");
            int contador = 0;
            while (rs.next()) {
                id[contador] = rs.getInt(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return id;
    }
    
    public int[] telefonoPersonal() {
        int[] telefono = new int[conteoParaPersonal()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select telefono from dbo.Personal;");
            int contador = 0;
            while (rs.next()) {
                telefono[contador] = rs.getInt(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return telefono;
    }
    
    public String[] nombrePersonal() {
        String[] nombre = new String[conteoParaPersonal()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select nombre from dbo.Personal;");
            int contador = 0;
            while (rs.next()) {
                nombre[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nombre;
    }
    
    public String[] puestoContactos() {
        String[] puesto = new String[conteoParaPersonal()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select puesto from dbo.Personal;");
            int contador = 0;
            while (rs.next()) {
                puesto[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return puesto;
    }
}
